export const food = [
  { id: 0,
    name: 'Watermelon',
    price: 1,
    src: require('../img/watermelon.png'),
    taxes: ['IGV', 'ITS'] },
  { id: 1,
    name: 'Apple',
    price: 2,
    src: require('../img/apple.png'),
    taxes: ['IGV'] },
  { id: 2,
    name: 'Pear',
    price: 6,
    src: require('../img/pear.png'),
    taxes: ['ITS'] },
  { id: 3,
    name: 'Orange',
    price: 3,
    src: require('../img/orange.png'),
    taxes: ['ITS'] },
  { id: 4,
    name: 'Banana',
    price: 4,
    src: require('../img/banana.png'),
    taxes: ['ITS'] },
  { id: 5,
    name: 'Grapes',
    price: 5,
    src: require('../img/grapes.png'),
    taxes: ['ITS'] },
  { id: 6,
    name: 'Strawberry',
    price: 8,
    src: require('../img/strawberry.png'),
    taxes: ['IGV'] },
  { id: 7,
    name: 'Coconut',
    price: 7,
    src: require('../img/coconut.png'),
    taxes: ['IGV', 'ITS'] },
  { id: 8,
    name: 'Pineapple',
    price: 9,
    src: require('../img/pineapple.png'),
    taxes: ['ITS'],
  }
]

export const taxes = [
  { id: 0,
    name: 'IGV',
    src: require('../img/watermelon.png'),
  },
  { id: 1,
    name: 'ITS',
    src: require('../img/watermelon.png'),
  },
  { id: 2,
    name: 'SES',
    src: require('../img/watermelon.png'),
  },
]
